version: '3.8'

services:
  application:
    container_name: app
    command: python manage.py welcome
    build: ./services/application
    volumes:
      - ./images/:/app/images/:z
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/:z
      - ./services/postgres/base.sql:/docker-entrypoint-initdb.d/base.sql:z
    environment:
      - POSTGRES_USER=randwas12
      - POSTGRES_PASSWORD=randwas12
      - POSTGRES_DB=academydb

volumes:
  postgres: